# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='movies', to='actors.Actor'),
        ),
    ]
