# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_auto_20180816_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies', to='actors.Actor'),
        ),
    ]
