# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='Desc',
            field=models.TextField(default=datetime.datetime(2017, 8, 12, 13, 41, 52, 90588, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
