# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='Desc',
            field=models.TextField(),
        ),
    ]
