# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_auto_20170812_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='Desc',
        ),
    ]
