# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user2',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
