# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20170819_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
