# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_remove_user_confirm_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='New_message',
        ),
    ]
